name: ci
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: pip install poetry
      - name: Run poetry install
        run: poetry install
      - name: Run poetry run test
        run: poetry run test
